version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: codedeploy/application_stop.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/application_start.sh
      timeout: 180
      runas: ubuntu
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 300
      runas: ubuntu